#' Categorize Annual Rainfall Intensity
#'
#' @description
#' Classifies daily rainfall into "Low", "Medium", and "High" intensity categories 
#' based on user-provided spatial threshold maps.
#'
#' @details
#' This function uses highly optimized raster algebra to compare a daily rainfall 
#' stack against pixel-specific threshold maps. 
#' 
#' \strong{Mathematical Definition:}
#' For a daily precipitation stack \eqn{P_t}, and threshold maps \eqn{T_{low}} and \eqn{T_{high}}, 
#' the logical masks are defined as:
#' \deqn{M_{low} = (P_t > 1) \land (P_t \le T_{low})}
#' \deqn{M_{med} = (P_t > T_{low}) \land (P_t \le T_{high})}
#' \deqn{M_{high} = (P_t > T_{high})}
#' 
#' If \code{metric = "days"}, the function sums the masks to return the frequency of events. 
#' If \code{metric = "depth"}, it returns the total rainfall volume generated by those events:
#' \deqn{Depth_{high} = \sum_{t=1}^{N} (P_t \cdot M_{high})}
#'
#' @param nc_year Character path to a single year's NetCDF file OR a SpatRaster object.
#' @param threshold_map A 2-layer SpatRaster containing "Low" and "High" thresholds.
#' @param metric Character. Either "days" (count of events) or "depth" (total mm of rain). Default is "days".
#' @param plot_result Logical. If TRUE, plots the resulting 3-layer map.
#'
#' @return A 3-layer SpatRaster containing "Low_Intensity", "Medium_Intensity", and "High_Intensity" values.
#' @export
#' @importFrom terra rast
categorize_rainfall_intensity <- function(nc_year, 
                                          threshold_map, 
                                          metric = c("days", "depth"),
                                          plot_result = TRUE) {
  
  metric <- match.arg(metric)
  
  # --- 1. Load the single year daily data ---
  if (is.character(nc_year)) {
    if (!file.exists(nc_year)) stop("NetCDF file not found.")
    P <- terra::rast(nc_year)
  } else {
    P <- nc_year
  }
  
  # Extract the threshold layers
  T_low <- threshold_map[[1]]
  T_high <- threshold_map[[2]]
  
  message(paste("Categorizing rainfall intensities based on", metric, "..."))
  
  # --- 2. RASTER ALGEBRA (Logical Masks) ---
  mask_low  <- (P > 1) & (P <= T_low)
  mask_med  <- (P > T_low) & (P <= T_high)
  mask_high <- (P > T_high)
  
  # --- 3. CALCULATE METRICS ---
  # Notice: We just use standard sum() here. Because 'mask_low' is a SpatRaster,
  # the terra package automatically intercepts this and runs it in C++!
  if (metric == "days") {
    res_low  <- sum(mask_low, na.rm = TRUE)
    res_med  <- sum(mask_med, na.rm = TRUE)
    res_high <- sum(mask_high, na.rm = TRUE)
    
  } else if (metric == "depth") {
    res_low  <- sum(P * mask_low, na.rm = TRUE)
    res_med  <- sum(P * mask_med, na.rm = TRUE)
    res_high <- sum(P * mask_high, na.rm = TRUE)
  }
  
  # --- 4. STACK AND FORMAT ---
  result_stack <- c(res_low, res_med, res_high)
  names(result_stack) <- c(paste0("Low_Intensity_", metric),
                           paste0("Medium_Intensity_", metric),
                           paste0("High_Intensity_", metric))
  
  # --- 5. PLOTTING ---
  if (plot_result) {
    if (metric == "days") {
      pal <- grDevices::hcl.colors(50, "GnBu", rev = TRUE)
    } else {
      pal <- grDevices::hcl.colors(50, "YlGnBu", rev = TRUE)
    }
    
    terra::plot(result_stack, main = paste(names(result_stack)), col = pal)
  }
  
  return(result_stack)
}